### Numpy

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

## create array using numpy
##create a 1D array

arr1= np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [9]:
arr2= np.array([1,2,3,4,5])
arr2.reshape(1,5)  ## 1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [12]:
arr2 =np.array([[1,2,3,4,5,6]])
arr2.shape

(1, 6)

In [ ]:
## 2d array

arr2 =np.array([[1,2,3,4,5],[5,6,7,8,9]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [5 6 7 8 9]]
(2, 5)


In [14]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [16]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
## identity matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.transpose(arr2)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8],
       [5, 9]])

In [ ]:
## Attributes in Numpy Array

arr = np.array([[1,2,3],[4,5,6]])

print("Array: \n",arr)
print("shape:",arr.shape)
print("Numbers of dimensions:",arr.ndim)
print("Size (number of elements):",arr.size)
print("Data type:", arr.dtype)
print("Item size (in bytes):",arr.itemsize)

Array: 
 [[1 2 3]
 [4 5 6]]
shape: (2, 3)
Numbers of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


In [23]:
## Numpy Vectorized Operation

arr1 = np.array([1,2,3,4])
arr2 = np.array([10,20,30,40])

## Elements Wise Addition
print("Addition :",arr1 + arr2)

## Elements Wise Substraction
print("Substraction :",arr2 - arr1)

## Elements Wise Multiplication
print("Multiplication :",arr1 * arr2)

## Elements Wise Division
print("Division :",arr1 / arr2)

Addition : [11 22 33 44]
Substraction : [ 9 18 27 36]
Multiplication : [ 10  40  90 160]
Division : [0.1 0.1 0.1 0.1]


In [24]:
## Universal Function
arr = np.array([5,6,7,8,9])

## square root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

## Sine
print(np.sin(arr))

## natural log
print(np.log(arr))

[2.23606798 2.44948974 2.64575131 2.82842712 3.        ]
[ 148.4131591   403.42879349 1096.63315843 2980.95798704 8103.08392758]
[-0.95892427 -0.2794155   0.6569866   0.98935825  0.41211849]
[1.60943791 1.79175947 1.94591015 2.07944154 2.19722458]


In [25]:
## Array slicing and Indexing

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12,]])
print("Array :\n",arr)

Array :
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [32]:
print(arr[0][0])
print(arr[0:2,2:])

1
[[3 4]
 [7 8]]


In [43]:
print(arr[1:,3:],"\n")
print(arr[1:3,1:3])

[[ 8]
 [12]] 

[[ 6  7]
 [10 11]]


In [44]:
## Modify Array Elements
arr[0,0] =101
print(arr)

[[101   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [45]:
arr[1:]=1001
print(arr)

[[ 101    2    3    4]
 [1001 1001 1001 1001]
 [1001 1001 1001 1001]]


In [ ]:
## Stastical concepts -- Normalisation
## to have a mean of 0 and standard deviation of 1
data = np.array([1,2,3,4,5])

# Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

## Normalize the data
normalized_data = (data - mean)/std_dev
print("Normalized data :", normalized_data)

# Output:
# Normalized data :[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]

Normalized data : [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [50]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

#Mean
mean = np.mean(data)
print("Mean :",mean)

#Median
median = np.median(data)
print("Median :",median)

# standard deviation
std_dev = np.std(data)
print("Standard deviation :",std_dev)

##variance
variance = np.var(data)
print("variance :",variance)

Mean : 5.5
Median : 5.5
Standard deviation : 2.8722813232690143
variance : 8.25


In [56]:
## Logical operaton

data = np.array([1,2,3,4,5,6,7,8,9,10])

data[(data >= 5) & (data <= 8)]

array([5, 6, 7, 8])